Check Tempo version and image details

diff --git a/.tekton/integration-tests/pipelines/tempo-operator-e2e-test-pipeline-4-14.yaml b/.tekton/integration-tests/pipelines/tempo-operator-e2e-test-pipeline-4-14.yaml
--- a/.tekton/integration-tests/pipelines/tempo-operator-e2e-test-pipeline-4-14.yaml
+++ b/.tekton/integration-tests/pipelines/tempo-operator-e2e-test-pipeline-4-14.yaml
@@ -286,6 +286,153 @@ spec:
               check_operator_installed "servicemeshoperator" openshift-operators
               check_operator_installed "serverless-operator" openshift-serverless
               echo "Operator installation check completed."
+    - name: check-tempo-version
+      description: The task checks Tempo operator and operand version details and image info
+      runAfter:
+        - tempo-install
+      params:
+        - name: SNAPSHOT
+          value: $(params.SNAPSHOT)
+        - name: namespace
+          value: "$(params.namespace)"
+      taskSpec:
+        params:
+          - name: SNAPSHOT
+          - name: namespace
+            type: string
+        volumes:
+          - name: credentials
+            emptyDir: {}
+        steps:
+          - name: get-kubeconfig
+            ref:
+              resolver: git
+              params:
+                - name: url
+                  value: https://github.com/konflux-ci/build-definitions.git
+                - name: revision
+                  value: main
+                - name: pathInRepo
+                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
+            params:
+              - name: eaasSpaceSecretRef
+                value: $(tasks.eaas-provision-space.results.secretRef)
+              - name: clusterName
+                value: "$(tasks.provision-cluster.results.clusterName)"
+              - name: credentials
+                value: credentials
+          - name: check-version
+            env:
+              - name: KUBECONFIG
+                value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
+            volumeMounts:
+              - name: credentials
+                mountPath: /credentials
+            image: registry.redhat.io/openshift4/ose-cli:latest
+            script: |
+              #!/bin/bash
+              set -eu
+
+              # Variables for strings to check
+              JAEGER_QUERY_VERSION="gitVersion\":\"v1.62.0"
+              OPERATOR_VERSION="operator-version\":\"0.14.2"
+              OPERATOR_TEMPO_VERSION="tempo-version\":\"2.6.1"
+              OPERATOR_TEMPO_QUERY_VERSION="tempo-query-version\":\"2.6.1"
+              OPERAND_TEMPO_VERSION="tempo, version 2.6.1"
+
+              function log_cmd() {
+                  echo "\$ $*"
+                  "$@"
+              }
+              function exit_error() {
+                  >&2 echo -e "ERROR: $*"
+                  exit 1
+              }
+
+              function generate_random_name() {
+                  echo "random-name-$RANDOM"
+              }
+
+              function wait_for_pod_running() {
+                  local pod_name=$1
+                  local namespace=$2
+                  while true; do
+                      pod_status=$(oc get pod $pod_name -n $namespace -o jsonpath='{.status.phase}')
+                      if [ "$pod_status" == "Running" ]; then
+                          break
+                      elif [ "$pod_status" == "Failed" ] || [ "$pod_status" == "Unknown" ]; then
+                          exit_error "Pod $pod_name failed to start. Status: $pod_status"
+                      fi
+                      sleep 2
+                  done
+              }
+
+              function check_strings_in_logs() {
+                  local pod_name=$1
+                  local namespace=$2
+                  shift 2
+                  local strings=("$@")
+
+                  logs=$(oc logs pod/$pod_name -n $namespace)
+                  for string in "${strings[@]}"; do
+                      if ! echo "$logs" | grep -q "$string"; then
+                          exit_error "String '$string' not found in logs of pod $pod_name"
+                      fi
+                  done
+              }
+
+              echo "Kubeconfig file"
+              cat $KUBECONFIG
+
+              echo "Install kubectl and oc"
+              cd /tmp/ \
+              && curl -L -o oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/openshift-client-linux-amd64-rhel8.tar.gz \
+              && tar -xvzf oc.tar.gz \
+              && chmod +x kubectl oc \
+              && mv oc kubectl /usr/local/bin/
+
+              echo
+              echo
+              echo "TEMPO IMAGE DETAILS AND VERSION INFO"
+              echo
+
+              tempo_images=$(oc get deployment tempo-operator-controller -n openshift-tempo-operator -o yaml | grep -o "registry.redhat.io/rhosdt/.*" | sort | uniq)
+              [ $(echo "$tempo_images" | wc -l) -eq 6 ] || exit_error "Expected 6 images, found:\n$tempo_images"
+
+              oc project default
+
+              for image in $tempo_images; do
+                  oc image info "$image" --filter-by-os linux/amd64
+                  echo
+
+                  random_name=$(generate_random_name)
+
+                  if [[ $image == *tempo-rhel8@* ]]; then
+                      log_cmd oc run $random_name --image=$image -- --version
+                      wait_for_pod_running $random_name default
+                      log_cmd oc logs pod/$random_name
+                      check_strings_in_logs $random_name default "$OPERAND_TEMPO_VERSION"
+                  elif [[ $image == *tempo-gateway-rhel8* || $image == *tempo-gateway-opa-rhel8* || $image == *tempo-query-rhel8* ]]; then
+                      echo "SKIPPED: $image doesn't have a version command"
+                  elif [[ $image == *tempo-rhel8-operator@* ]]; then
+                      log_cmd oc run $random_name --image=$image -- version
+                      wait_for_pod_running $random_name default
+                      log_cmd oc logs pod/$random_name
+                      check_strings_in_logs $random_name default "$OPERATOR_VERSION" "$OPERATOR_TEMPO_VERSION" "$OPERATOR_TEMPO_QUERY_VERSION"
+                  elif [[ $image == *tempo-jaeger-query-rhel8@* ]]; then
+                      log_cmd oc run $random_name --image=$image -- version
+                      wait_for_pod_running $random_name default
+                      log_cmd oc logs pod/$random_name
+                      check_strings_in_logs $random_name default "$JAEGER_QUERY_VERSION"
+                  else
+                      log_cmd oc run $random_name --image=$image -- version
+                      wait_for_pod_running $random_name default
+                      log_cmd oc logs pod/$random_name
+                  fi
+
+                  echo
+                  echo
+              done
     - name: tempo-e2e-tests
       description: Task to run tests from service repository
       runAfter:
